### ISSUE TITLE
Verificar se o período de inscrição está bom

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/saspi#1]
O período está definido na seção 5

**Comment by raunerlucas** [comment]
Quanto ao período de inscrição já foi feita a pergunta para os organizadores, a espera de resposta!
Mas os mesmo solicitam que seja criado um componente(Seguindo o modelo do "LOL" e do "Free-Fire") para inscrições virtuais da seguintes modalidade: 
* Tênis de mesa * & * Xadrez *

**Comment by raunerlucas** [comment]
Quanto ao período  de inscrição segundo a Aline, presidente do centro acadêmico está de acordo;
Subi a o componente de inscrição referente ao jogo de Xadrez, estou a espera de outro dados pra fazer o mesmo a respeito do
"Tênis_de_Mesa".

Em meu ultimo push fiz alteração nos links de inscrições do jogo Free-Fire, LoL pois os formulários de inscrição(Forms) estavam em uma conta que não temos mais acesso. E foi adicionado um area pra inscrição no jogo de Xadrez, vou add o do Tênis de Mesa quando o regulamento estiver pronto e o forms estiver de acordo. E por te a possibilidade ter o jogo de Valorant estou 
esperando, pra o caso de subir os dois ao mesmo tempo.

Cordialmente: Rauner Amaral

**Comment by raunerlucas** [comment]
Boa noite professor eu coloquei o capos de inscrição pra Tênis de mesa e o jogo de Valorant( não tinha sido solicitado oficialmente).
