### ISSUE TITLE
Adicionar link para YouTube do CA ou da Semana Acadêmica

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/saspi#2]

**Comment by raunerlucas** [comment]
Link do canal no YouTube: 
https://www.youtube.com/channel/UCQCIMhDJYCUNBGPHqFhQ0xQ

**Comment by raunerlucas** [comment]
Fiz alteração do link do canal do youtube  que estava incorreto; E coloquei o email especifico da semana acadêmica no campo de certificados para facilitar no caso de duvidas referentes o tema.
