### ISSUE TITLE
Verificar inscrição do Xadrez

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/saspi#5]
As inscrições para o Xadrez só iniciam após o término das inscrições normais, em 17/10?
Ver https://github.com/iftopalmas/saspi/blame/main/README.adoc#L201

Se é isso mesmo, deve usar a variável `{termino_inscricao}` no lugar da data fixa.
Colocar dados que mudam no meio do documento torna difícil localizar e atualizar estes dados,
principalmente quando eles estão repetidos em vários locais.

**Comment by raunerlucas** [comment]
Entendi... Ok vou mudar... nos decidimos dar uma semana completa de inscrição pro jogos para dar mais tempo para os participantes se inscreverem,  e não ficarem reclamando sem motivo.

**Comment by raunerlucas** [comment]
Prof fiz como o senhor especificou no email, é assim mesmo?

**Comment by manoelcampos** [comment]
As inscrições para qualquer atividade deve seguir o mesmo perído de inscrição do evento em geral. Não tem como definir datas diferentes. O sistema de eventos não permite isso.
Assim, não deve ter informações sobre período de inscrição do xadres ou qualquer outra atividade.
A única informação deve ser do período de inscrição geral. 
Alterei este período, mas remova esta informação sobre período de inscrição específico para o xadres.

**Comment by raunerlucas** [comment]
Acredito que entendi vou providenciar

**Comment by raunerlucas** [comment]
Professor eu fiz o que eu entedi... tirei o que especificava o período de inscrições de todos dos jogos, o senhor pode conferir pra mim se era isso mesmo ?

**Comment by manoelcampos** [comment]
> Prof fiz como o senhor especificou no email, é assim mesmo?

Pra ele fechar a issue automaticamente, tem que colocar apenas "Close #XXXX" na primeira linha.
Como você colocou o texto da issue junto, ele não fechou. Mas ok, fechei aqui.

**Comment by manoelcampos** [comment]
> Professor eu fiz o que eu entedi... tirei o que especificava o período de inscrições de todos dos jogos, o senhor pode conferir pra mim se era isso mesmo ?

Isso. So tem um local com período de inscrição.
