### ISSUE TITLE
Cadastrar programação

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/saspi#8]
Preencher as tabelas de programação conforme as informações em https://si.ifto.edu.br/evento/1267/
ou a partir da nossa planilha (pois lá tem informações detalhadas como o nome do palestrante, que pode não aparecer na página acima).

**Comment by manoelcampos** [comment]
As inscrições abrem amanhã. É preciso atualizar o site o quanto antes.

**Comment by raunerlucas** [comment]
Ok já estou fazendo... Já já subo pra main

**Comment by raunerlucas** [comment]
Professor não consegui localizar onde estavam listados os requisitos pra os minicursos

**Comment by manoelcampos** [comment]
Não tem essa informação. Vou apagar a tabela respectiva.
